name: ecos_communicator
description: A library to easily communicate with the ECoS command station.
version: 1.0.0+2

homepage: https://pub.dev/packages/ecos_communicator
repository: https://github.com/TheKingDave/ecos_communicator
issue_tracker: https://github.com/TheKingDave/ecos_communicator/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.3
  collection: ^1.14.13

dev_dependencies:
  test: ^1.14.4
